### ISSUE TITLE
MUNavigation改变导航栏样式侧滑引发错误

### ISSUE THREAD

**Issue by yleson** [Jeykit/MUKit#8]
1.进入MUNavigation改变导航栏样式
2.侧滑一下，样式变成了上一个页面的样式

**Comment by Jeykit** [comment]
这个会在下一个版本更改过，目前正在测试中.........

**Comment by Jeykit** [comment]
目前已经修复了，还可以像京东、淘宝等热门应用的导航一样具备全屏侧滑。
