### ISSUE TITLE
MUCollectionViewManager 添加addFooterRefreshing上拉加载没反应

### ISSUE THREAD

**Issue by liyin2016** [Jeykit/MUKit#9]

**Comment by Jeykit** [comment]
有的 你看看是不是UICollectionView的frame设置问题，或者截图给我看一下

**Comment by liyin2016** [comment]
当collectionview个数超出屏幕的时候就可以上拉加载，如果个数刚好可以在手机屏幕完全显示的时候上拉加载就失去反应了，是不是在外部要设置alwaysBounceVertical属性的呀？

**Comment by Jeykit** [comment]
是的 collectionview默认禁止了这个属性
